[tools]
rojo = "rojo-rbx/rojo@7.4.2"
lune = "lune-org/lune@0.8.6"
selene = "Kampfkarren/selene@0.27.1"
wally = "UpliftGames/wally@0.3.2"
stylua = "Johnnymorganz/stylua@0.20.0"
wally-package-types = "johnnymorganz/wally-package-types@1.3.2"
darklua = "seaofvoices/darklua@0.13.1"
