[tools]
rojo = "rojo-rbx/rojo@7.4.1"
lune = "lune-org/lune@0.8.4"
selene = "Kampfkarren/selene@0.27.1"
stylua = "JohnnyMorganz/StyLua@0.20.0"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "johnnymorganz/wally-package-types@1.3.1"
darklua = "seaofvoices/darklua@0.13.0"
