[package]
name = "tijne/vfxeditor"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
fusion = "elttob/fusion@0.2.0"
Lucide = "virtualbutfake/lucide-roblox@1.1.2"
themeFramework = "virtualbutfake/themeframework@0.0.146"
tailwind = "virtualbutfake/tailwind@0.0.135"
fusionUtils = "virtualbutfake/fusionutils@0.0.142"
studioComponents = "virtualbutfake/studiocomponents@0.0.208"