[package]
name = "tijne/vfxeditor"
version = "1.0.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
fusion = "elttob/fusion@0.2.0"
lucide = "virtualbutfake/lucide-roblox@1.1.3"
themeFramework = "virtualbutfake/theme-framework@0.1.6"
tailwind = "virtualbutfake/tailwind@0.1.1"
fusionUtils = "virtualbutfake/fusion-utils@0.1.2"
fusionComponents = "virtualbutfake/fusion-components@0.1.16"
signal = "sleitnick/signal@2.0.1"
